import { CategoryData, LinkItem } from './types';

// Utility to generate large datasets for UI testing/demonstration
const generateMoreLinks = (categoryPrefix: string, count: number): LinkItem[] => {
  return Array.from({ length: count }, (_, i) => ({
    name: `${categoryPrefix} Resource ${i + 1}`,
    url: `https://example.com/resource/${categoryPrefix.toLowerCase().replace(/\s+/g, '-')}/${i + 1}`,
    description: `A premium curated resource #${i + 1} for ${categoryPrefix}. Verified for 2025.`,
    isPremium: Math.random() > 0.8 // Randomly mark some as premium
  }));
};

// Base curated lists
const aiGeneral: LinkItem[] = [
  { name: 'ChatGPT', url: 'https://chat.openai.com' },
  { name: 'Claude', url: 'https://claude.ai' },
  { name: 'Gemini', url: 'https://gemini.google.com' },
  { name: 'Microsoft Copilot', url: 'https://copilot.microsoft.com' },
  { name: 'Perplexity', url: 'https://www.perplexity.ai' },
  { name: 'Grok', url: 'https://grok.x.ai' },
  { name: 'Meta AI', url: 'https://www.meta.ai' },
  { name: 'Pi.ai', url: 'https://pi.ai' },
  { name: 'DeepSeek', url: 'https://chat.deepseek.com' },
  { name: 'Poe', url: 'https://poe.com' },
  { name: 'You.com', url: 'https://you.com' },
  { name: 'Phind', url: 'https://www.phind.com' },
  { name: 'Le Chat Mistral', url: 'https://chat.mistral.ai' },
  { name: 'HuggingChat', url: 'https://huggingface.co/chat' },
  { name: 'Character.ai', url: 'https://beta.character.ai' },
  { name: 'Jasper', url: 'https://www.jasper.ai' },
  { name: 'Copy.ai', url: 'https://www.copy.ai' },
  { name: 'Rytr', url: 'https://rytr.me' },
  { name: 'Writesonic', url: 'https://writesonic.com' },
  { name: 'ChatSonic', url: 'https://writesonic.com/chat' },
];

const aiImage: LinkItem[] = [
  { name: 'Midjourney', url: 'https://www.midjourney.com' },
  { name: 'DALL-E 3', url: 'https://openai.com/dall-e-3' },
  { name: 'Ideogram', url: 'https://ideogram.ai' },
  { name: 'Leonardo.ai', url: 'https://leonardo.ai' },
  { name: 'Adobe Firefly', url: 'https://firefly.adobe.com' },
  { name: 'Stable Diffusion WebUI', url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui' },
  { name: 'Flux (fal.ai)', url: 'https://fal.ai/models/flux' },
  { name: 'Recraft', url: 'https://www.recraft.ai' },
  { name: 'Canva Magic Media', url: 'https://www.canva.com/magic-media' },
  { name: 'Civitai', url: 'https://civitai.com' },
  { name: 'NightCafe', url: 'https://creator.nightcafe.studio' },
  { name: 'DreamStudio', url: 'https://beta.dreamstudio.ai' },
  { name: 'Artbreeder', url: 'https://www.artbreeder.com' },
  { name: 'Playground AI', url: 'https://playgroundai.com' },
  { name: 'Krea.ai', url: 'https://www.krea.ai' }
];

const aiVideo: LinkItem[] = [
  { name: 'Runway ML', url: 'https://runwayml.com' },
  { name: 'Pika Labs', url: 'https://pika.art' },
  { name: 'Sora (OpenAI)', url: 'https://openai.com/sora' },
  { name: 'Kling AI', url: 'https://kling.kuaishou.com' },
  { name: 'Luma Dream Machine', url: 'https://lumalabs.ai/dream-machine' },
  { name: 'Synthesia', url: 'https://www.synthesia.io' },
  { name: 'HeyGen', url: 'https://www.heygen.com' },
  { name: 'Descript', url: 'https://www.descript.com' },
  { name: 'InVideo AI', url: 'https://invideo.io/ai' },
  { name: 'Pictory', url: 'https://pictory.ai' },
  { name: 'CapCut AI', url: 'https://www.capcut.com' },
  { name: 'Fliki', url: 'https://fliki.ai' },
  { name: 'Opus Clip', url: 'https://www.opus.pro' },
  { name: 'Kaiber', url: 'https://kaiber.ai' },
  { name: 'Wonder Studio', url: 'https://wonderdynamics.com' }
];

export const aiToolsData: CategoryData = {
  id: 'ai-tools',
  title: 'AI Tools',
  iconName: 'Bot',
  description: 'The definitive collection of Artificial Intelligence tools for chat, image, and video generation.',
  sections: [
    {
      title: 'General Chatbots & Assistants',
      items: [...aiGeneral, ...generateMoreLinks('AI Chat', 1700)]
    },
    {
      title: 'Image Generation',
      items: [...aiImage, ...generateMoreLinks('AI Image', 1650)]
    },
    {
      title: 'Video Generation',
      items: [...aiVideo, ...generateMoreLinks('AI Video', 1650)]
    }
  ]
};

const videoEditingLinks: LinkItem[] = [
  { name: 'Adobe Premiere Pro', url: 'https://www.adobe.com/products/premiere.html' },
  { name: 'DaVinci Resolve', url: 'https://www.blackmagicdesign.com/products/davinciresolve' },
  { name: 'Final Cut Pro', url: 'https://www.apple.com/final-cut-pro' },
  { name: 'CapCut', url: 'https://www.capcut.com' },
  { name: 'Clipchamp', url: 'https://clipchamp.com' },
  { name: 'VEED.IO', url: 'https://www.veed.io' },
  { name: 'InVideo', url: 'https://invideo.io' },
  { name: 'WeVideo', url: 'https://www.wevideo.com' },
  { name: 'FlexClip', url: 'https://www.flexclip.com' },
  { name: 'Kapwing', url: 'https://www.kapwing.com' },
  { name: 'Filmora', url: 'https://filmora.wondershare.com' },
  { name: 'HitFilm', url: 'https://fxhome.com/product/hitfilm' },
  { name: 'Lightworks', url: 'https://lwks.com' },
  { name: 'Shotcut', url: 'https://shotcut.org' },
  { name: 'OpenShot', url: 'https://www.openshot.org' },
  { name: 'iMovie', url: 'https://www.apple.com/imovie' },
  { name: 'PowerDirector', url: 'https://www.cyberlink.com/products/powerdirector-video-editing-software' },
  { name: 'Vegas Pro', url: 'https://www.vegascreativesoftware.com' },
  { name: 'Descript', url: 'https://www.descript.com' },
  { name: 'Runway', url: 'https://runwayml.com' },
  { name: 'Opus Clip', url: 'https://www.opus.pro' },
  { name: 'Munch', url: 'https://www.getmunch.com' },
  { name: 'Gling', url: 'https://gling.ai' },
  { name: 'Adobe After Effects', url: 'https://www.adobe.com/products/aftereffects.html' },
  { name: 'Blender', url: 'https://www.blender.org' },
  { name: 'Natron', url: 'https://natrongithub.github.io' },
  { name: 'Kdenlive', url: 'https://kdenlive.org' },
  { name: 'Olive Video Editor', url: 'https://olivevideoeditor.org' },
  { name: 'Animoto', url: 'https://animoto.com' },
  { name: 'Magisto', url: 'https://www.magisto.com' },
  { name: 'Renderforest', url: 'https://www.renderforest.com' },
  { name: 'Biteable', url: 'https://biteable.com' },
  { name: 'Promo.com', url: 'https://promo.com' },
  { name: 'Wideo', url: 'https://wideo.co' },
  { name: 'Moovly', url: 'https://www.moovly.com' },
  { name: 'Powtoon', url: 'https://www.powtoon.com' },
  { name: 'Vimeo Create', url: 'https://vimeo.com/create' },
  { name: 'Canva Video', url: 'https://www.canva.com/video-editor' },
  { name: 'Typito', url: 'https://typito.com' },
  { name: 'Headliner', url: 'https://www.headliner.app' },
  { name: 'Wave.video', url: 'https://wave.video' },
  { name: 'Hippo Video', url: 'https://www.hippovideo.io' },
  { name: 'Lumen5', url: 'https://lumen5.com' },
  { name: 'Steve.ai', url: 'https://www.steve.ai' },
  { name: 'Elai.io', url: 'https://elai.io' },
  { name: 'Hour One', url: 'https://hourone.ai' },
  { name: 'D-ID', url: 'https://www.d-id.com' },
  { name: 'Movavi', url: 'https://www.movavi.com' },
  { name: 'Pinnacle Studio', url: 'https://www.pinnaclesys.com' },
  { name: 'Avid Media Composer', url: 'https://www.avid.com/media-composer' }
];

export const videoEditingData: CategoryData = {
  id: 'video-editing',
  title: 'Video Editing',
  iconName: 'Film',
  description: 'Top professional software and online editors for creators.',
  items: [...videoEditingLinks, ...generateMoreLinks('Editor', 5000)]
};

const educationLinks: LinkItem[] = [
  { name: 'Khan Academy', url: 'https://www.khanacademy.org' },
  { name: 'Coursera', url: 'https://www.coursera.org' },
  { name: 'edX', url: 'https://www.edx.org' },
  { name: 'Duolingo', url: 'https://www.duolingo.com' },
  { name: 'Wikipedia', url: 'https://www.wikipedia.org' },
  { name: 'MIT OpenCourseWare', url: 'https://ocw.mit.edu' },
  { name: 'Codecademy', url: 'https://www.codecademy.com' },
  { name: 'Brilliant', url: 'https://brilliant.org' },
  { name: 'TED-Ed', url: 'https://ed.ted.com' },
  { name: 'Quizlet', url: 'https://quizlet.com' },
  { name: 'BBC Bitesize', url: 'https://www.bbc.co.uk/bitesize' },
  { name: 'Harvard Online', url: 'https://online-learning.harvard.edu' },
  { name: 'Udemy', url: 'https://www.udemy.com' },
  { name: 'Udacity', url: 'https://www.udacity.com' },
  { name: 'Pluralsight', url: 'https://www.pluralsight.com' },
  { name: 'Skillshare', url: 'https://www.skillshare.com' },
  { name: 'MasterClass', url: 'https://www.masterclass.com' },
  { name: 'FutureLearn', url: 'https://www.futurelearn.com' },
  { name: 'Academic Earth', url: 'https://academicearth.org' },
  { name: 'Stanford Online', url: 'https://online.stanford.edu' },
  { name: 'OpenCulture', url: 'https://www.openculture.com' },
  { name: 'Project Gutenberg', url: 'https://www.gutenberg.org' },
  { name: 'Internet Archive', url: 'https://archive.org' },
  { name: 'Wolfram Alpha', url: 'https://www.wolframalpha.com' },
  { name: 'Chegg', url: 'https://www.chegg.com' },
  { name: 'Course Hero', url: 'https://www.coursehero.com' },
  { name: 'Scribd', url: 'https://www.scribd.com' },
  { name: 'Grammarly', url: 'https://www.grammarly.com' },
  { name: 'Hemingway Editor', url: 'https://hemingwayapp.com' },
  { name: 'Notion', url: 'https://www.notion.so' },
  { name: 'Evernote', url: 'https://evernote.com' },
  { name: 'Anki', url: 'https://apps.ankiweb.net' },
  { name: 'Brainly', url: 'https://brainly.com' },
  { name: 'Kahoot!', url: 'https://kahoot.com' },
  { name: 'Edmodo', url: 'https://new.edmodo.com' },
  { name: 'Google Scholar', url: 'https://scholar.google.com' },
  { name: 'ResearchGate', url: 'https://www.researchgate.net' },
  { name: 'JSTOR', url: 'https://www.jstor.org' },
  { name: 'Academia.edu', url: 'https://www.academia.edu' },
  { name: 'Zotero', url: 'https://www.zotero.org' },
  { name: 'Mendeley', url: 'https://www.mendeley.com' },
  { name: 'EndNote', url: 'https://endnote.com' },
  { name: 'Overleaf', url: 'https://www.overleaf.com' },
  { name: 'Code.org', url: 'https://code.org' },
  { name: 'FreeCodeCamp', url: 'https://www.freecodecamp.org' },
  { name: 'W3Schools', url: 'https://www.w3schools.com' },
  { name: 'GeeksforGeeks', url: 'https://www.geeksforgeeks.org' },
  { name: 'Stack Overflow', url: 'https://stackoverflow.com' },
  { name: 'MDN Web Docs', url: 'https://developer.mozilla.org' },
  { name: 'Scrimba', url: 'https://scrimba.com' }
];

export const educationData: CategoryData = {
  id: 'education',
  title: 'Education',
  iconName: 'GraduationCap',
  description: 'Unlock knowledge with the worlds best learning platforms.',
  items: [...educationLinks, ...generateMoreLinks('Edu', 5000)]
};

const healthLinks: LinkItem[] = [
  { name: 'MedlinePlus', url: 'https://medlineplus.gov' },
  { name: 'Mayo Clinic', url: 'https://www.mayoclinic.org' },
  { name: 'WebMD', url: 'https://www.webmd.com' },
  { name: 'NIH', url: 'https://www.nih.gov' },
  { name: 'CDC', url: 'https://www.cdc.gov' },
  { name: 'WHO', url: 'https://www.who.int' },
  { name: 'Healthline', url: 'https://www.healthline.com' },
  { name: 'Harvard Health', url: 'https://www.health.harvard.edu' },
  { name: 'Cleveland Clinic', url: 'https://my.clevelandclinic.org' },
  { name: 'Everyday Health', url: 'https://www.everydayhealth.com' },
  { name: 'Johns Hopkins Medicine', url: 'https://www.hopkinsmedicine.org' },
  { name: 'Medical News Today', url: 'https://www.medicalnewstoday.com' },
  { name: 'Drugs.com', url: 'https://www.drugs.com' },
  { name: 'RxList', url: 'https://www.rxlist.com' },
  { name: 'Psychology Today', url: 'https://www.psychologytoday.com' },
  { name: 'Verywell Health', url: 'https://www.verywellhealth.com' },
  { name: 'Verywell Mind', url: 'https://www.verywellmind.com' },
  { name: 'Verywell Fit', url: 'https://www.verywellfit.com' },
  { name: 'Men\'s Health', url: 'https://www.menshealth.com' },
  { name: 'Women\'s Health', url: 'https://www.womenshealthmag.com' },
  { name: 'Prevention', url: 'https://www.prevention.com' },
  { name: 'Self', url: 'https://www.self.com' },
  { name: 'Shape', url: 'https://www.shape.com' },
  { name: 'MyFitnessPal', url: 'https://www.myfitnesspal.com' },
  { name: 'Fitbit', url: 'https://www.fitbit.com' },
  { name: 'Strava', url: 'https://www.strava.com' },
  { name: 'Headspace', url: 'https://www.headspace.com' },
  { name: 'Calm', url: 'https://www.calm.com' },
  { name: 'BetterHelp', url: 'https://www.betterhelp.com' },
  { name: 'Talkspace', url: 'https://www.talkspace.com' },
  { name: 'Zocdoc', url: 'https://www.zocdoc.com' },
  { name: 'GoodRx', url: 'https://www.goodrx.com' },
  { name: 'PubMed', url: 'https://pubmed.ncbi.nlm.nih.gov' },
  { name: 'UpToDate', url: 'https://www.uptodate.com' },
  { name: 'Medscape', url: 'https://www.medscape.com' },
  { name: 'Epocrates', url: 'https://www.epocrates.com' },
  { name: 'Doximity', url: 'https://www.doximity.com' },
  { name: 'American Heart Assoc.', url: 'https://www.heart.org' },
  { name: 'American Cancer Soc.', url: 'https://www.cancer.org' },
  { name: 'Diabetes.org', url: 'https://diabetes.org' },
  { name: 'NIMH', url: 'https://www.nimh.nih.gov' },
  { name: 'Planned Parenthood', url: 'https://www.plannedparenthood.org' },
  { name: 'Red Cross', url: 'https://www.redcross.org' },
  { name: 'Doctors Without Borders', url: 'https://www.doctorswithoutborders.org' },
  { name: 'UNICEF', url: 'https://www.unicef.org' },
  { name: 'Nutrition.gov', url: 'https://www.nutrition.gov' },
  { name: 'EatRight', url: 'https://www.eatright.org' },
  { name: 'Sleep Foundation', url: 'https://www.sleepfoundation.org' },
  { name: 'Mind.org.uk', url: 'https://www.mind.org.uk' },
  { name: 'NHS', url: 'https://www.nhs.uk' }
];

export const healthData: CategoryData = {
  id: 'health',
  title: 'Health',
  iconName: 'HeartPulse',
  description: 'Trusted medical information and wellness resources.',
  items: [...healthLinks, ...generateMoreLinks('Health', 5000)]
};

const sportsLinks: LinkItem[] = [
  { name: 'ESPN', url: 'https://www.espn.com' },
  { name: 'Bleacher Report', url: 'https://bleacherreport.com' },
  { name: 'Yahoo Sports', url: 'https://sports.yahoo.com' },
  { name: 'CBS Sports', url: 'https://www.cbssports.com' },
  { name: 'NBC Sports', url: 'https://www.nbcsports.com' },
  { name: 'The Athletic', url: 'https://theathletic.com' },
  { name: 'BBC Sport', url: 'https://www.bbc.com/sport' },
  { name: 'Sky Sports', url: 'https://www.skysports.com' },
  { name: 'SI.com', url: 'https://www.si.com' },
  { name: 'Fox Sports', url: 'https://www.foxsports.com' },
  { name: 'Deadspin', url: 'https://deadspin.com' },
  { name: 'SBNation', url: 'https://www.sbnation.com' },
  { name: 'NBA.com', url: 'https://www.nba.com' },
  { name: 'NFL.com', url: 'https://www.nfl.com' },
  { name: 'MLB.com', url: 'https://www.mlb.com' },
  { name: 'NHL.com', url: 'https://www.nhl.com' },
  { name: 'FIFA', url: 'https://www.fifa.com' },
  { name: 'UEFA', url: 'https://www.uefa.com' },
  { name: 'Formula 1', url: 'https://www.formula1.com' },
  { name: 'MotoGP', url: 'https://www.motogp.com' },
  { name: 'UFC', url: 'https://www.ufc.com' },
  { name: 'PGA Tour', url: 'https://www.pgatour.com' },
  { name: 'ATP Tour', url: 'https://www.atptour.com' },
  { name: 'WTA Tennis', url: 'https://www.wtatennis.com' },
  { name: 'Cricbuzz', url: 'https://www.cricbuzz.com' },
  { name: 'ESPNcricinfo', url: 'https://www.espncricinfo.com' },
  { name: 'RugbyPass', url: 'https://www.rugbypass.com' },
  { name: 'Planet Rugby', url: 'https://www.planetrugby.com' },
  { name: 'Eurosport', url: 'https://www.eurosport.com' },
  { name: 'beIN SPORTS', url: 'https://www.beinsports.com' },
  { name: 'DAZN', url: 'https://www.dazn.com' },
  { name: 'Red Bull', url: 'https://www.redbull.com' },
  { name: 'X Games', url: 'https://xgames.com' },
  { name: 'Olympic Channel', url: 'https://olympics.com' },
  { name: 'Strava', url: 'https://www.strava.com' },
  { name: 'Goal.com', url: 'https://www.goal.com' },
  { name: 'OneFootball', url: 'https://onefootball.com' },
  { name: '90min', url: 'https://www.90min.com' },
  { name: 'FourFourTwo', url: 'https://www.fourfourtwo.com' },
  { name: 'Transfermarkt', url: 'https://www.transfermarkt.com' },
  { name: 'Flashscore', url: 'https://www.flashscore.com' },
  { name: 'LiveScore', url: 'https://www.livescore.com' },
  { name: 'Sofascore', url: 'https://www.sofascore.com' },
  { name: 'DraftKings', url: 'https://www.draftkings.com' },
  { name: 'FanDuel', url: 'https://www.fanduel.com' },
  { name: 'Rivals', url: 'https://n.rivals.com' },
  { name: '247Sports', url: 'https://247sports.com' },
  { name: 'MaxPreps', url: 'https://www.maxpreps.com' },
  { name: 'Hudl', url: 'https://www.hudl.com' },
  { name: 'Runner\'s World', url: 'https://www.runnersworld.com' }
];

export const sportsData: CategoryData = {
  id: 'sports',
  title: 'Sports',
  iconName: 'Trophy',
  description: 'Live scores, news, and highlights from the world of sports.',
  items: [...sportsLinks, ...generateMoreLinks('Sports', 5000)]
};

const technologyLinks: LinkItem[] = [
  { name: 'TechCrunch', url: 'https://techcrunch.com' },
  { name: 'Wired', url: 'https://www.wired.com' },
  { name: 'The Verge', url: 'https://www.theverge.com' },
  { name: 'Engadget', url: 'https://www.engadget.com' },
  { name: 'CNET', url: 'https://www.cnet.com' },
  { name: 'Ars Technica', url: 'https://arstechnica.com' },
  { name: 'Gizmodo', url: 'https://gizmodo.com' },
  { name: 'Reuters Tech', url: 'https://www.reuters.com/technology' },
  { name: 'MIT Tech Review', url: 'https://www.technologyreview.com' },
  { name: 'VentureBeat', url: 'https://venturebeat.com' },
  { name: 'ZDNet', url: 'https://www.zdnet.com' },
  { name: 'PCMag', url: 'https://www.pcmag.com' },
  { name: 'Tom\'s Hardware', url: 'https://www.tomshardware.com' },
  { name: 'Tom\'s Guide', url: 'https://www.tomsguide.com' },
  { name: 'Android Authority', url: 'https://www.androidauthority.com' },
  { name: 'Android Central', url: 'https://www.androidcentral.com' },
  { name: '9to5Google', url: 'https://9to5google.com' },
  { name: '9to5Mac', url: 'https://9to5mac.com' },
  { name: 'MacRumors', url: 'https://www.macrumors.com' },
  { name: 'AppleInsider', url: 'https://appleinsider.com' },
  { name: 'Windows Central', url: 'https://www.windowscentral.com' },
  { name: 'The Next Web', url: 'https://thenextweb.com' },
  { name: 'Mashable', url: 'https://mashable.com' },
  { name: 'Digital Trends', url: 'https://www.digitaltrends.com' },
  { name: 'TechRadar', url: 'https://www.techradar.com' },
  { name: 'Trusted Reviews', url: 'https://www.trustedreviews.com' },
  { name: 'Pocket-lint', url: 'https://www.pocket-lint.com' },
  { name: 'SlashGear', url: 'https://www.slashgear.com' },
  { name: 'AnandTech', url: 'https://www.anandtech.com' },
  { name: 'Hacker News', url: 'https://news.ycombinator.com' },
  { name: 'Product Hunt', url: 'https://www.producthunt.com' },
  { name: 'GitHub', url: 'https://github.com' },
  { name: 'Stack Overflow', url: 'https://stackoverflow.com' },
  { name: 'Dev.to', url: 'https://dev.to' },
  { name: 'Smashing Mag', url: 'https://www.smashingmagazine.com' },
  { name: 'CSS-Tricks', url: 'https://css-tricks.com' },
  { name: 'A List Apart', url: 'https://alistapart.com' },
  { name: 'IEEE Spectrum', url: 'https://spectrum.ieee.org' },
  { name: 'NASA', url: 'https://www.nasa.gov' },
  { name: 'Space.com', url: 'https://www.space.com' },
  { name: 'New Scientist', url: 'https://www.newscientist.com' },
  { name: 'Scientific American', url: 'https://www.scientificamerican.com' },
  { name: 'Futurism', url: 'https://futurism.com' },
  { name: 'Recode', url: 'https://www.vox.com/recode' },
  { name: 'Protocol', url: 'https://www.protocol.com' },
  { name: 'The Information', url: 'https://www.theinformation.com' },
  { name: 'Fast Company', url: 'https://www.fastcompany.com' },
  { name: 'Inc.', url: 'https://www.inc.com' },
  { name: 'Forbes Tech', url: 'https://www.forbes.com/innovation' },
  { name: 'Bloomberg Tech', url: 'https://www.bloomberg.com/technology' }
];

export const technologyData: CategoryData = {
  id: 'technology',
  title: 'Technology',
  iconName: 'Cpu',
  description: 'Latest tech news, reviews, and innovations.',
  items: [...technologyLinks, ...generateMoreLinks('Tech', 5000)]
};

const newsLinks: LinkItem[] = [
  { name: 'CNN', url: 'https://www.cnn.com' },
  { name: 'BBC News', url: 'https://www.bbc.com/news' },
  { name: 'Reuters', url: 'https://www.reuters.com' },
  { name: 'AP News', url: 'https://apnews.com' },
  { name: 'New York Times', url: 'https://www.nytimes.com' },
  { name: 'The Guardian', url: 'https://www.theguardian.com' },
  { name: 'Al Jazeera', url: 'https://www.aljazeera.com' },
  { name: 'NBC News', url: 'https://www.nbcnews.com' },
  { name: 'Fox News', url: 'https://www.foxnews.com' },
  { name: 'Washington Post', url: 'https://www.washingtonpost.com' },
  { name: 'Wall Street Journal', url: 'https://www.wsj.com' },
  { name: 'USA Today', url: 'https://www.usatoday.com' },
  { name: 'Bloomberg', url: 'https://www.bloomberg.com' },
  { name: 'CNBC', url: 'https://www.cnbc.com' },
  { name: 'NPR', url: 'https://www.npr.org' },
  { name: 'PBS NewsHour', url: 'https://www.pbs.org/newshour' },
  { name: 'CBS News', url: 'https://www.cbsnews.com' },
  { name: 'ABC News', url: 'https://abcnews.go.com' },
  { name: 'Sky News', url: 'https://news.sky.com' },
  { name: 'France 24', url: 'https://www.france24.com' },
  { name: 'Deutsche Welle', url: 'https://www.dw.com' },
  { name: 'Euronews', url: 'https://www.euronews.com' },
  { name: 'CBC News', url: 'https://www.cbc.ca/news' },
  { name: 'Global News', url: 'https://globalnews.ca' },
  { name: 'The Independent', url: 'https://www.independent.co.uk' },
  { name: 'The Telegraph', url: 'https://www.telegraph.co.uk' },
  { name: 'Financial Times', url: 'https://www.ft.com' },
  { name: 'The Economist', url: 'https://www.economist.com' },
  { name: 'Time', url: 'https://time.com' },
  { name: 'Newsweek', url: 'https://www.newsweek.com' },
  { name: 'Politico', url: 'https://www.politico.com' },
  { name: 'The Hill', url: 'https://thehill.com' },
  { name: 'Axios', url: 'https://www.axios.com' },
  { name: 'Vox', url: 'https://www.vox.com' },
  { name: 'HuffPost', url: 'https://www.huffpost.com' },
  { name: 'BuzzFeed News', url: 'https://www.buzzfeednews.com' },
  { name: 'Vice', url: 'https://www.vice.com' },
  { name: 'Slate', url: 'https://slate.com' },
  { name: 'The Atlantic', url: 'https://www.theatlantic.com' },
  { name: 'New Yorker', url: 'https://www.newyorker.com' },
  { name: 'ProPublica', url: 'https://www.propublica.org' },
  { name: 'Democracy Now!', url: 'https://www.democracynow.org' },
  { name: 'Christian Science Monitor', url: 'https://www.csmonitor.com' },
  { name: 'South China Morning Post', url: 'https://www.scmp.com' },
  { name: 'Times of India', url: 'https://timesofindia.indiatimes.com' },
  { name: 'The Japan Times', url: 'https://www.japantimes.co.jp' },
  { name: 'Kyiv Independent', url: 'https://kyivindependent.com' },
  { name: 'Moscow Times', url: 'https://www.themoscowtimes.com' },
  { name: 'Haaretz', url: 'https://www.haaretz.com' },
  { name: 'Jerusalem Post', url: 'https://www.jpost.com' }
];

export const newsData: CategoryData = {
  id: 'news',
  title: 'News',
  iconName: 'Newspaper',
  description: 'Breaking news and in-depth reporting from around the globe.',
  items: [...newsLinks, ...generateMoreLinks('News', 5000)]
};

const jobsLinks: LinkItem[] = [
  { name: 'LinkedIn', url: 'https://www.linkedin.com' },
  { name: 'Indeed', url: 'https://www.indeed.com' },
  { name: 'Glassdoor', url: 'https://www.glassdoor.com' },
  { name: 'Monster', url: 'https://www.monster.com' },
  { name: 'ZipRecruiter', url: 'https://www.ziprecruiter.com' },
  { name: 'SimplyHired', url: 'https://www.simplyhired.com' },
  { name: 'CareerBuilder', url: 'https://www.careerbuilder.com' },
  { name: 'Upwork', url: 'https://www.upwork.com' },
  { name: 'Fiverr', url: 'https://www.fiverr.com' },
  { name: 'Toptal', url: 'https://www.toptal.com' },
  { name: 'Behance', url: 'https://www.behance.net/jobs' },
  { name: 'Dribbble', url: 'https://dribbble.com/jobs' },
  { name: 'We Work Remotely', url: 'https://weworkremotely.com' },
  { name: 'Remote OK', url: 'https://remoteok.com' },
  { name: 'FlexJobs', url: 'https://www.flexjobs.com' },
  { name: 'Wellfound (AngelList)', url: 'https://wellfound.com' },
  { name: 'Hired', url: 'https://hired.com' },
  { name: 'Dice', url: 'https://www.dice.com' },
  { name: 'USAJOBS', url: 'https://www.usajobs.gov' },
  { name: 'Handshake', url: 'https://joinhandshake.com' },
  { name: 'Freelancer', url: 'https://www.freelancer.com' },
  { name: 'Guru', url: 'https://www.guru.com' },
  { name: 'Jooble', url: 'https://jooble.org' },
  { name: 'Ladders', url: 'https://www.theladders.com' },
  { name: 'Snagajob', url: 'https://www.snagajob.com' },
  { name: 'Idealist', url: 'https://www.idealist.org' },
  { name: 'Craigslist', url: 'https://www.craigslist.org' },
  { name: 'Robert Half', url: 'https://www.roberthalf.com' },
  { name: 'Kforce', url: 'https://www.kforce.com' },
  { name: 'Randstad', url: 'https://www.randstadusa.com' }
];

export const jobsData: CategoryData = {
  id: 'jobs',
  title: 'Jobs',
  iconName: 'Briefcase',
  description: 'Find your dream career with top job boards and freelance platforms.',
  items: [...jobsLinks, ...generateMoreLinks('Job', 1000)]
};

const businessLinks: LinkItem[] = [
  { name: 'Forbes', url: 'https://www.forbes.com' },
  { name: 'Bloomberg', url: 'https://www.bloomberg.com' },
  { name: 'Business Insider', url: 'https://www.businessinsider.com' },
  { name: 'Harvard Business Review', url: 'https://hbr.org' },
  { name: 'The Wall Street Journal', url: 'https://www.wsj.com' },
  { name: 'Entrepreneur', url: 'https://www.entrepreneur.com' },
  { name: 'Inc.', url: 'https://www.inc.com' },
  { name: 'Fast Company', url: 'https://www.fastcompany.com' },
  { name: 'CNBC', url: 'https://www.cnbc.com' },
  { name: 'Financial Times', url: 'https://www.ft.com' },
  { name: 'MarketWatch', url: 'https://www.marketwatch.com' },
  { name: 'Yahoo Finance', url: 'https://finance.yahoo.com' },
  { name: 'Slack', url: 'https://slack.com' },
  { name: 'Zoom', url: 'https://zoom.us' },
  { name: 'Microsoft Teams', url: 'https://www.microsoft.com/en-us/microsoft-teams/group-chat-software' },
  { name: 'Asana', url: 'https://asana.com' },
  { name: 'Trello', url: 'https://trello.com' },
  { name: 'Salesforce', url: 'https://www.salesforce.com' },
  { name: 'HubSpot', url: 'https://www.hubspot.com' },
  { name: 'Shopify', url: 'https://www.shopify.com' },
  { name: 'Stripe', url: 'https://stripe.com' },
  { name: 'PayPal', url: 'https://www.paypal.com' },
  { name: 'Square', url: 'https://squareup.com' },
  { name: 'QuickBooks', url: 'https://quickbooks.intuit.com' },
  { name: 'Xero', url: 'https://www.xero.com' },
  { name: 'Monday.com', url: 'https://monday.com' },
  { name: 'Notion', url: 'https://www.notion.so' },
  { name: 'ClickUp', url: 'https://clickup.com' },
  { name: 'Airtable', url: 'https://www.airtable.com' },
  { name: 'Intercom', url: 'https://www.intercom.com' }
];

export const businessData: CategoryData = {
  id: 'business',
  title: 'Business',
  iconName: 'Building2',
  description: 'Essential business news, finance tools, and enterprise software.',
  items: [...businessLinks, ...generateMoreLinks('Business', 1000)]
};

export const allCategories: CategoryData[] = [
  aiToolsData,
  videoEditingData,
  educationData,
  healthData,
  sportsData,
  technologyData,
  newsData,
  jobsData,
  businessData
];
